--- 
language: php

php:
  - 5.3

script:
  - mkdir -p build/logs
  - phpunit --coverage-clover build/logs/clover.xml

before_script:
  - composer require --dev satooshi/php-coveralls:dev-master
  - composer install
  - mysql -e 'create database `test-functest`;'
  - mysql test-functest < tests/test_data/database.sql

after_script:
  - php vendor/bin/coveralls -v
