---
language: php

sudo: false

php:
  - 7.1

env:
  - DEPS=normal
  - DEPS=highest
  - DEPS=lowest

matrix:
  fast_finish: true

branches:
  only:
    - master

cache:
  directories:
  - $HOME/.composer/cache

notifications:
  email: false
  slack:
    secure: ixWu6kWtNIlzzdImpu4MdvGYpA6ZPp/dQpMAp6FDO2oHHB55J9ossBYtVtBXPCDs9OxqfQl2yqbE+TkhfIfkZqIbhvX2+CiIomvYSKZDvryUlCfbfV29behmSVIVYvg3b8Tba+nAyZeJA2guUyAy02WGr3n4I+PDgZC3Wa/mv94=

install:
  - if [ "$DEPS" = "normal" ]; then composer install --no-interaction; fi;
  - if [ "$DEPS" = "highest" ]; then composer update --no-interaction; fi;
  - if [ "$DEPS" = "lowest" ]; then composer update --no-interaction --prefer-lowest --prefer-stable; fi;

before_script:
  - mkdir -p build/logs
  - mysql -e 'create database if not exists `test-functest`;'
  - mysql test-functest < tests/test_data/database.sql

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
